example_reflection: ShowClass Class Reference
ShowClass Class Reference
Static Public Member Functions
static void main (String[] args) throws ClassNotFoundException
static void print_class (Class<?> c)
static String (Class<?> t)
static String modifiers (int m)
static void print_field (Field f)
static void print_method_or_constructor (Member member)
Detailed Description
A program that displays a class synopsis for the named class
Author
David Flanagan
Robert C. Duvall
Definition at line 19 of file ShowClass.java.
Member Function Documentation
static void ShowClass.main (String[] args) throws ClassNotFoundException static
The main method. Print info about the named class
Definition at line 23 of file ShowClass.java.
References print_class().
static String ShowClass.modifiers (int m) static
Return a string version of modifiers, handling spaces nicely.
Definition at line 98 of file ShowClass.java.
Referenced by print_field(), and print_method_or_constructor().
static void ShowClass.print_class (Class<?> c) static
Display the modifiers, name, superclass and interfaces of a class or interface. Then go and list all constructors, fields, and methods.
Definition at line 31 of file ShowClass.java.
References print_field(), and print_method_or_constructor().
Referenced by main().
static void ShowClass.print_field (Field f) static
Print the modifiers, type, and name of a field
Definition at line 108 of file ShowClass.java.
References modifiers().
Referenced by print_class().
static void ShowClass.print_method_or_constructor (Member member) static
Print the modifiers, return type, name, parameter types and exception type of a method or constructor. Note the use of the Member interface to allow this method to work with both Method and Constructor objects
Definition at line 118 of file ShowClass.java.
References modifiers().
Referenced by print_class().
static ShowClass.String (Class<?> t) static
Return name of an interface or primitive type, handling arrays.
Definition at line 86 of file ShowClass.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/example_reflection/repository/src/ShowClass.java